version: "3.9"
services:

  kafka-test:
    image: 'bitnami/kafka:3.6'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-test:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-test:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 2

  mongodb-test:
    image: mongo:7.0.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:mongouser
      - MONGO_INITDB_ROOT_PASSWORD:mongopass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  app-test:
    image: data_microservices-test:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://mongodb-test:27017
      - MONGO_DBNAME=productdb_test
      - SECRET_USER=testuser
      - SECRET_PASSWORD=testpassword
      - SECRET_KEY=testkey
      - KAFKA_URI=kafka-test
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/login || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    depends_on:
      mongodb-test:
        condition: service_healthy
      kafka-test:
        condition: service_healthy

  test:
    image: integration-test:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    environment:
      - MONGO_URI=mongodb://mongodb-test:27017
      - MONGO_DBNAME=productdb_test
      - SECRET_USER=testuser
      - SECRET_PASSWORD=testpassword
      - SECRET_KEY=testkey
      - KAFKA_URI=kafka-test
    depends_on:
      - app-test
      - mongodb-test
      - kafka-test
    command: "go test -race"
