version: "3.9"
services:

  mongodb:
    image: mongo:7.0.3
    restart: always
    ports:
      - 27017:27017
    environment:
      # todo chagne to env variable
      - MONGO_INITDB_ROOT_USERNAME:mongo_write
      - MONGO_INITDB_ROOT_PASSWORD:write1243omf9dnsO
      - MONGO_INITDB_DATABASE:products
    volumes:
      - ../db:/data/db

  # app:
  #   image: data_microservices:latest
  #   ports:
  #     - 8080:8080
  #   # environment:
  #   #   - MONGO_INITDB_ROOT_USERNAME=root
  #   #   - MONGO_INITDB_ROOT_PASSWORD=123456
  #   #   - MONGO_INITDB_DATABASE=products
  #   #   - MONGO_INITDB_USERNAME=admin
  #   #   - MONGO_INITDB_PASSWORD=admin
  #   depends_on:
  #     - mongodb

  mongo-client:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_write
      - ME_CONFIG_MONGODB_ADMINPASSWORD=write1243omf9dnsO
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb